import type { ContactCaptchaQuestion } from "@/lib/contact-captcha";

export const contactCaptchaQuestions: ContactCaptchaQuestion[] = [
  { id: "math-7-plus-5", prompt: "What is 7 + 5?", correctAnswer: "12" },
  { id: "math-9-minus-3", prompt: "What is 9 - 3?", correctAnswer: "6" },
  { id: "math-8-plus-6", prompt: "What is 8 + 6?", correctAnswer: "14" },
  { id: "math-10-minus-4", prompt: "What is 10 - 4?", correctAnswer: "6" },
  { id: "math-11-plus-2", prompt: "What is 11 + 2?", correctAnswer: "13" },
  { id: "math-15-minus-7", prompt: "What is 15 - 7?", correctAnswer: "8" },
  { id: "math-6-times-4", prompt: "What is 6 x 4?", correctAnswer: "24" },
  { id: "math-3-times-5", prompt: "What is 3 x 5?", correctAnswer: "15" },
  { id: "math-9-plus-8", prompt: "What is 9 + 8?", correctAnswer: "17" },
  { id: "math-18-minus-9", prompt: "What is 18 - 9?", correctAnswer: "9" },
  { id: "math-7-times-3", prompt: "What is 7 x 3?", correctAnswer: "21" },
  { id: "math-12-plus-9", prompt: "What is 12 + 9?", correctAnswer: "21" },
  { id: "math-20-minus-8", prompt: "What is 20 - 8?", correctAnswer: "12" },
  { id: "math-5-times-6", prompt: "What is 5 x 6?", correctAnswer: "30" },
  { id: "math-14-plus-11", prompt: "What is 14 + 11?", correctAnswer: "25" },
  { id: "math-16-minus-7", prompt: "What is 16 - 7?", correctAnswer: "9" },
  {
    id: "india-capital",
    prompt: "What is the capital city of India?",
    correctAnswer: "New Delhi",
    wrongAnswers: ["Mumbai", "Bengaluru", "Chennai"],
  },
  {
    id: "mumbai-country",
    prompt: "Mumbai belongs to which country?",
    correctAnswer: "India",
    wrongAnswers: ["Nepal", "Sri Lanka", "Bangladesh"],
  },
  {
    id: "bengaluru-state",
    prompt: "Which state is Bengaluru in?",
    correctAnswer: "Karnataka",
    wrongAnswers: ["Kerala", "Tamil Nadu", "Maharashtra"],
  },
  {
    id: "mysuru-state",
    prompt: "Which state is Mysuru in?",
    correctAnswer: "Karnataka",
    wrongAnswers: ["Goa", "Kerala", "Telangana"],
  },
  {
    id: "chennai-state",
    prompt: "Which state is Chennai in?",
    correctAnswer: "Tamil Nadu",
    wrongAnswers: ["Karnataka", "Kerala", "Andhra Pradesh"],
  },
  {
    id: "hyderabad-state",
    prompt: "Which state is Hyderabad in?",
    correctAnswer: "Telangana",
    wrongAnswers: ["Andhra Pradesh", "Karnataka", "Maharashtra"],
  },
  {
    id: "goa-country",
    prompt: "Goa is in which country?",
    correctAnswer: "India",
    wrongAnswers: ["Nepal", "Bhutan", "Sri Lanka"],
  },
  {
    id: "kerala-country",
    prompt: "Kerala is in which country?",
    correctAnswer: "India",
    wrongAnswers: ["Pakistan", "Bangladesh", "Nepal"],
  },
  {
    id: "delhi-language",
    prompt: "Which language is widely used as a common official language in India?",
    correctAnswer: "Hindi",
    wrongAnswers: ["Spanish", "German", "Japanese"],
  },
  {
    id: "taj-city",
    prompt: "The Taj Mahal is in which city?",
    correctAnswer: "Agra",
    wrongAnswers: ["Jaipur", "Lucknow", "Surat"],
  },
  {
    id: "gateway-city",
    prompt: "The Gateway of India is in which city?",
    correctAnswer: "Mumbai",
    wrongAnswers: ["Pune", "Delhi", "Mysuru"],
  },
  {
    id: "redfort-city",
    prompt: "The Red Fort is in which city?",
    correctAnswer: "Delhi",
    wrongAnswers: ["Chennai", "Hyderabad", "Kochi"],
  },
];
